### ISSUE TITLE
test262 work items

### ISSUE THREAD

**Issue by cjtenny** [tc39/proposal-temporal#1398]
In #1393 @ptomato discussed wanting a place to track tests that will need to be added to test262. We decided a single meta-issue should suffice. Feel free to edit, add, and sign up for any items! This is a living list and should be expected to grow.

- [ ] From #1393: Does Temporal check that retrieved methods from user-supplied objects are callable?
- [ ] From #1393: `timeZone.getInstantFor` throw for non-Temporal.Instant values
- [ ] #1047: calendar.fields return includes 'calendar'
- [ ] #1047: calendar.fields return includes non-calendar fields, e.g. 'nanoseconds'
- [ ] #1134: Time zones for Temporal.now()
- [ ] From #1397: Observable lookups & calls for timeZone objects from other temporal methods
- [ ] #1388: Calendar order of operations (with and)? without Intl
- [ ] From #1396: `PlainMonthDay.prototype.toPlainDate` correctly handle `[['year', undefined]]` for input fields
- [ ] From #1489: Test [CalendarFields calls](https://github.com/tc39/proposal-temporal/pull/1489#discussion_r615068081), including with [fields added](https://github.com/tc39/proposal-temporal/pull/1489#discussion_r615082466), and [getPossibleInstantsFor type checks](https://github.com/tc39/proposal-temporal/pull/1489#discussion_r615141800)
- [ ] Check fast-paths from #1428:
  - [ ] PlainDateTime -> PlainTime
  - [ ] ZonedDateTime -> TimeZone
  - [ ] PlainTime -> Calendar
  - [ ] PlainDate -> relativeTo object
  - [ ] Callers of GetOptionalTemporalCalendar and ToTemporalMonthDay, with a not-previously-covered Temporal object (e.g. ToTemporalDate with some object like `Object.assign(new Temporal.MonthDay(1, 1), { year: 2000 }))`
  - [ ] ZonedDateTime -> PlainDate, PlainDateTime, PlainTime
- [ ] Check that with() methods don't call getters on Temporal objects
- [ ] Check all remaining callers of GetPossibleInstantsFor with checkTimeZonePossibleInstantsIterable
- [ ] Check that things of the wrong type in an iterable (calendar.fields return, calendar.fields input, timeZone.getPossibleInstantsFor return) throw before exhausting the iterator
- [ ] Check that `calendar.fields` is always called with the correct list of fields
- [ ] Check that Gets occur for every extra field returned by `calendar.fields`
- [ ] Check that `toString` is not called in CalendarEquals, TimeZoneEquals, ConsolidateCalendars if the two calendars are the same object (#1425 point 2)
- [ ] Check that any calendar/timezone method that receives an internally-created options object, doesn't cause lookups on Object.prototype (#1424)
- [ ] Check that property accesses on null-prototype objects created internally in Temporal don't cause lookups on Object.prototype (https://github.com/tc39/proposal-temporal/pull/1875/files#r748524136)
- [ ] Add tests for ParseTemporalDurationString overflowing one of the fields to infinity (e.g., `PT99999....99999Y`)
- [ ] Add tests for BalanceDuration causing a Duration field to overflow to infinity and throwing:
  - [ ] AddDuration (3x instances)
  - [ ] PlainTime.until()/since()
  - [ ] PlainDateTime.until()/since()
- [ ] Add tests for CreateDurationRecord / CreateTemporalDuration combining mixed signs or overflowing and throwing:
  - [ ] AddDateTime
  - [ ] new Temporal.Duration()
  - [ ] Duration.from()
  - [ ] Duration.with()
  - [ ] RoundDuration (3rd instance)
- [ ] Verify that there is no possible test case that would cause CreateDurationRecord / CreateTemporalDuration to combine values from different sources having different signs:
  - [ ] AdjustRoundedDurationDays (last instance)
  - [ ] AddDuration (2nd instance)
  - [ ] ZonedDateTime.until()/since()
- [ ] Verify that there is no possible test case that would cause CreateDurationRecord / CreateTemporalDuration to overflow to infinity:
  - [ ] DifferenceZonedDateTime (last instance)
  - [ ] RoundDuration
- [ ] Check that all `(optionName)-undefined.js` tests also test plain function objects
- [ ] Figure out a sequence of custom calendar and time zone return values that exercise the checks in https://github.com/tc39/proposal-temporal/pull/2387

**Comment by ptomato** [comment]
I consolidated this list into https://github.com/tc39/test262/issues/3002.
