### ISSUE TITLE
Work items

### ISSUE THREAD

**Issue by ptomato** [tc39/proposal-temporal#711]
As discussed in the June 26 meeting, here are some work items that we'd like to get done. Sign yourself up as your availability allows! This list will continue to be updated

- [ ] Upgrade guide / comparison with other libraries
  - @ryzokuken 
- [ ] Shim, in order to import tests from other libraries or do conversions to and from other libraries' types (#104, #556)
- [ ] Production-quality polyfill after Stage 3
- [x] Write documentation page for DST best practices
  - @justingrant 
- [x] Finish the spec
  - @ryzokuken, @ptomato 
- [x] Add other Intl-supported calendars
  - @sffc?
- [ ] Complete test262 suite after Stage 3

**Comment by ptomato** [comment]
We haven't been using this issue to organize work on the proposal recently, so it's outdated - let's close it.
